spring:
 application:
  name: EurekaServer

server:
 port: 8761
 
eureka:
 instance:
  hostname: localhost
 client:
  registerWithEureka: true #This can be set as a false also. 
  fetchRegistry: false
 server:
  enableSelfPreservation: false
